POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlZWt1cHBpIiwiaWQiOiI1ZmEwMmZmNjdlNmFjNzAyMTgwY2E3MjEiLCJpYXQiOjE2MDQ1NTQxMTB9.u0mXnkXJrJq7xownmUMIrfC4bMfmAm_X11IL9xobfbk

{
  "author": "Teekuppityyppi",
  "title": "Teekupin blogi kaksi",
  "url": "teekuppi.com",
  "likes": 3
}