POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhYWphIiwiaWQiOiI1ZmE3NmIzNDcxMjQ4MzJiNjQwYzhjYWMiLCJpYXQiOjE2MDQ4MDc2OTF9.2kowaQM-Kn29gCGIouYWNPvswM1FdPmzXdA-9JkRCeI

{
  "author": "Teekuppityyppi",
  "title": "Teekupin blogi SADIASHIODSAJIOSADJISDAJI",
  "url": "teekuppi.com",
  "likes": 3
}